### ISSUE TITLE
Use document.currentScript to get the current running script

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/scripts#16]
Instead of using this:

https://github.com/simpleanalytics/scripts/blob/3b270cef5f4353c526cb85fa7defb045f1f816b6/src/default.js#L287-L288

We can use:

```js
var scriptElement = doc.currentScript || doc.querySelector('script[src*="' + baseUrl + '"]');
```

- We can now support multiple scripts on one page with multiple settings

### Tasks
- [x] Update script to use above syntax
- [ ] Add to the docs: not supported in IE (https://caniuse.com/document-currentscript) but it uses regressions
- [ ] Update proxy docs page
